ec2nodeclassName: default
nodeRoleName: ""
discoveryTagValue: ""
amiAlias: al2023@latest
spotPreferred: false
expireAfter: 720h
consolidateAfter: 1m
cpuLimit: "32"
memoryLimit: "64Gi"

# List of requirement objects: { key, operator, values }
primaryRequirements: []
fallbackRequirements: []
