name: Promote Dev

on:
  push:
    branches:
      - main
    paths:
      - "enviroments/dev/**"
      - "modules/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-dev:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: dev
      terraform_dir: enviroments/dev
